// packages/click-outsider-svelte/ClickOutsiderWrapper.svelte
<script>
  import ClickOutsider from "click-outsider";
  import { onMount, onDestroy, createEventDispatcher } from "svelte";

  const dispatch = createEventDispatcher();

  let elementRef;

  onMount(() => ClickOutsider.add(elementRef, () => dispatch("click-outside")));

  onDestroy(() => ClickOutsider.remove(elementRef));
  console.log($$props);
</script>

<div bind:this={elementRef} {...$$props}>
  <slot />
</div>

// packages/click-outsider-vue/ClickOutsiderWrapper.vue
<template>
  <div v-bind="$attrs" ref="elementRef">
    <slot />
  </div>
</template>
<script setup lang="ts">
import ClickOutsider from "click-outsider";
import { onUnmounted, onMounted, ref } from "vue";

const emit = defineEmits<{
  (e: "on-click-outside"): void;
}>();

const elementRef = ref();

onMounted(() =>
  ClickOutsider.add(elementRef.value, () => emit("on-click-outside"))
);

onUnmounted(() => ClickOutsider.remove(elementRef.value));
</script>
